### PR TITLE
feat(get_bmc_facts): support both user/pass/auth

### PR DESCRIPTION
**Pull request by glimchb**
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

### CODE REVIEW

**Comment by sandersms** [comment]
Should CodeQL be included in the automated testing for this repository?

Can the README markdown-lint error be corrected to resolve the required failing test?

**Comment by glimchb** [comment]
> Should CodeQL be included in the automated testing for this repository?

I see `Did not detect any languages to analyze. Please update input in workflow or check that GitHub detects the correct languages in your repository.`
 
need to research how to fix it... 

> Can the README markdown-lint error be corrected to resolve the required failing test?

this readme was auto-generated... need to think what is the best approach here...  next time we auto-generate it will return again... maybe ignore this specific file... don't know...

**Review by sachin-apa — APPROVED** [review]
This looks good, But we can add a common way of creating session and invoke that here instead of using basic auth to be consistent.. May be a future changes.

**Comment by glimchb** [comment]
> This looks good, But we can add a common way of creating session and invoke that here instead of using basic auth to be consistent.. May be a future changes.

yep, added new role already 
https://github.com/opiproject/ansible-opi-dpu/blob/main/roles/bmc_session/tasks/main.yml

**Pull request merged**
